#!/usr/bin/env python3
"""
build.py — turn rants/*.md into static HTML.

Workflow:
    1. write a new rant as  rants/<slug>.md  (see rants/README.md for the format)
    2. run                  python3 build.py
    3. it regenerates       rants/<slug>.html  (one per post)
       and                  rants.html         (the index, newest first)

No dependencies — standard library only. The rest of the site
(index.html, resume.html, work.html) is hand-written and untouched.
"""

import os
import re
import glob

HERE = os.path.dirname(os.path.abspath(__file__))
RANTS_DIR = os.path.join(HERE, "rants")

MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]

GENERATED = "<!-- generated by build.py, edit the .md source, not this file -->"


# ----------------------------------------------------------------------
# helpers
# ----------------------------------------------------------------------
def escape(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def attr(s):
    return escape(s).replace('"', "&quot;")


def fmt_date(d):
    """2026-07-17 -> 'July 17, 2026' (falls back to the raw string)."""
    try:
        y, m, day = d.split("-")
        return "%s %d, %s" % (MONTHS[int(m) - 1], int(day), int(y))
    except Exception:
        return d


# ----------------------------------------------------------------------
# markdown -> html  (a focused subset: enough for prose)
# ----------------------------------------------------------------------
def inline(text):
    codes = []

    def stash(m):
        codes.append(escape(m.group(1)))
        return "\x00%d\x00" % (len(codes) - 1)

    text = re.sub(r"`([^`]+)`", stash, text)       # protect inline code
    text = escape(text)                             # escape everything else
    text = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)",     # [text](url)
                  lambda m: '<a href="%s">%s</a>' % (m.group(2), m.group(1)), text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"<em>\1</em>", text)
    text = re.sub(r"(?<!\w)_([^_\n]+)_(?!\w)", r"<em>\1</em>", text)
    text = re.sub(r"\x00(\d+)\x00",                 # restore inline code
                  lambda m: "<code>%s</code>" % codes[int(m.group(1))], text)
    return text


def md_to_html(md):
    lines = md.split("\n")
    out = []
    para = []
    i, n = 0, len(lines)

    def flush():
        if para:
            text = " ".join(para).strip()
            if text:
                out.append("<p>" + inline(text) + "</p>")
            para.clear()

    while i < n:
        line = lines[i]
        s = line.strip()

        if s.startswith("```"):                     # fenced code block
            flush()
            code, i = [], i + 1
            while i < n and not lines[i].strip().startswith("```"):
                code.append(lines[i])
                i += 1
            i += 1
            out.append("<pre><code>" + escape("\n".join(code)) + "</code></pre>")
            continue

        if s == "":
            flush()
            i += 1
            continue

        if re.match(r"^(-{3,}|\*{3,}|_{3,})$", s):   # horizontal rule
            flush()
            out.append("<hr />")
            i += 1
            continue

        m = re.match(r"^(#{1,6})\s+(.*)$", s)        # heading
        if m:
            flush()
            lvl = len(m.group(1))
            out.append("<h%d>%s</h%d>" % (lvl, inline(m.group(2).strip()), lvl))
            i += 1
            continue

        if s.startswith(">"):                        # blockquote
            flush()
            quote = []
            while i < n and lines[i].strip().startswith(">"):
                quote.append(re.sub(r"^\s*>\s?", "", lines[i]).strip())
                i += 1
            out.append("<blockquote>" + inline(" ".join(quote)) + "</blockquote>")
            continue

        if re.match(r"^([-*+]|\d+\.)\s+", s):        # list (ordered or not)
            flush()
            ordered = bool(re.match(r"^\d+\.\s+", s))
            mine = r"^\d+\.\s+" if ordered else r"^[-*+]\s+"
            other = r"^[-*+]\s+" if ordered else r"^\d+\.\s+"
            items = []
            while i < n:
                cs = lines[i].strip()
                if cs == "":                         # blank line ends the list
                    i += 1
                    break
                if re.match(mine, cs):               # new item of this list
                    items.append(re.sub(mine, "", cs))
                elif re.match(other, cs):            # a different list starts
                    break
                elif items:                          # lazy continuation of an item
                    items[-1] += " " + cs
                else:
                    break
                i += 1
            tag = "ol" if ordered else "ul"
            out.append("<%s>%s</%s>" % (
                tag, "".join("<li>%s</li>" % inline(x) for x in items), tag))
            continue

        para.append(s)
        i += 1

    flush()
    return "\n".join(out)


# ----------------------------------------------------------------------
# frontmatter
# ----------------------------------------------------------------------
def parse(md_text):
    meta, body = {}, md_text
    if md_text.startswith("---"):
        parts = md_text.split("---", 2)
        if len(parts) >= 3:
            for row in parts[1].strip().split("\n"):
                if ":" in row:
                    k, v = row.split(":", 1)
                    meta[k.strip()] = v.strip()
            body = parts[2].lstrip("\n")
    return meta, body


# ----------------------------------------------------------------------
# templates
# ----------------------------------------------------------------------
FONTS = ('<link rel="preconnect" href="https://fonts.googleapis.com" />\n'
         '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n'
         '<link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,600;12..96,700;12..96,800&family=IBM+Plex+Mono:wght@400;500&family=Public+Sans:wght@400;500;600&display=swap" rel="stylesheet" />')

FOOTER = '''  <footer id="contact">
    <p class="label">contact</p>
    <a class="big-link js-email-reveal" data-e="zbp.yvnzt@srveovarz" href="#" role="button">Click to reveal email →</a>
    <p class="also">
      Disagree with something here? Tell me, I like being argued with.
    </p>
    <div class="colophon">
      <span>© 2026 Meni Brief · Seattle, WA</span>
      <span>
        <a href="https://www.linkedin.com/in/meni-brief/" target="_blank" rel="noopener">LinkedIn</a>
        &nbsp;·&nbsp;
        <a href="https://www.semanticscholar.org/author/Meni-Brief/2217252086" target="_blank" rel="noopener">Semantic Scholar</a>
      </span>
    </div>
  </footer>'''

POST_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
{generated}
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{title} · Meni Brief</title>
<meta name="description" content="{desc}" />
{fonts}
<link rel="stylesheet" href="../styles.css" />
</head>
<body>

<div class="wrap">

  <header class="top">
    <button type="button" class="wordmark">hello world!</button>
    <nav aria-label="Site">
      <a href="../index.html">home</a>
      <a href="../resume.html">resumé</a>
      <a href="../rants.html" aria-current="page">rants</a>
      <a href="../work.html">work</a>
    </nav>
  </header>

  <article class="post">
    <a class="back" href="../rants.html">← all rants</a>
    <h1>{title}</h1>
    <p class="post-meta">{date_display}</p>
    <div class="post-body">
{body}
    </div>
  </article>

{footer}

</div>

<script src="../script.js"></script>

</body>
</html>
'''

INDEX_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
{generated}
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Meni Brief · Rants</title>
<meta name="description" content="Writing and strong opinions by Meni (Menachem) Brief, on AI, building, and whatever else." />
{fonts}
<link rel="stylesheet" href="styles.css" />
</head>
<body>

<div class="wrap">

  <header class="top">
    <button type="button" class="wordmark">hello world!</button>
    <nav aria-label="Site">
      <a href="index.html">home</a>
      <a href="resume.html">resumé</a>
      <a href="rants.html" aria-current="page">rants</a>
      <a href="work.html">work</a>
    </nav>
  </header>

  <section class="hero slim" style="border-top: none;">
    <p class="eyebrow">Rants</p>
    <h1>Thinking out <span class="arrow">loud</span>.</h1>
    <p class="lede">
      Half-formed thoughts and strong opinions loosely held. Not polished, occasionally wrong, always mine.
      Cannot make any promises about whether they are worth your time.
    </p>
  </section>

  <section id="writing">
    <p class="label">writing</p>
{list}
  </section>

{footer}

</div>

<script src="script.js"></script>

</body>
</html>
'''

EMPTY_LIST = ('    <p class="lede" style="margin-top:0;color:var(--mute)">'
              'Nothing published yet. Check back soon.</p>')


# ----------------------------------------------------------------------
# build
# ----------------------------------------------------------------------
def build():
    posts = []
    for path in sorted(glob.glob(os.path.join(RANTS_DIR, "*.md"))):
        name = os.path.basename(path)
        if name.lower() == "readme.md":
            continue
        with open(path, encoding="utf-8") as f:
            meta, body = parse(f.read())
        if not meta.get("title"):
            print("  skip (no title frontmatter): %s" % name)
            continue

        slug = os.path.splitext(name)[0]
        title = meta["title"]
        date = meta.get("date", "")
        summary = meta.get("summary", "")
        date_display = fmt_date(date)
        desc = summary or title

        html = POST_TEMPLATE.format(
            generated=GENERATED,
            fonts=FONTS,
            footer=FOOTER,
            title=escape(title),
            desc=attr(desc),
            date_display=escape(date_display),
            body=md_to_html(body),
        )
        with open(os.path.join(RANTS_DIR, slug + ".html"), "w", encoding="utf-8") as f:
            f.write(html)
        posts.append({"slug": slug, "title": title, "date": date,
                      "date_display": date_display, "summary": summary})
        print("  wrote rants/%s.html" % slug)

    # remove generated pages whose .md source is gone (renamed / deleted)
    built = {p["slug"] for p in posts}
    for html in glob.glob(os.path.join(RANTS_DIR, "*.html")):
        slug = os.path.splitext(os.path.basename(html))[0]
        if slug not in built:
            os.remove(html)
            print("  removed orphan rants/%s.html" % slug)

    posts.sort(key=lambda p: p["date"], reverse=True)

    if posts:
        rows = []
        for p in posts:
            rows.append(
                '      <li><a href="rants/%s.html">\n'
                '        <span class="rtitle">%s</span>\n'
                '        <span class="rdate">%s</span>\n'
                '        <span class="rsum">%s</span>\n'
                '      </a></li>' % (
                    p["slug"], escape(p["title"]),
                    escape(p["date_display"]), escape(p["summary"])))
        listing = '    <ul class="rlist">\n' + "\n".join(rows) + "\n    </ul>"
    else:
        listing = EMPTY_LIST

    index = INDEX_TEMPLATE.format(
        generated=GENERATED, fonts=FONTS, footer=FOOTER, list=listing)
    with open(os.path.join(HERE, "rants.html"), "w", encoding="utf-8") as f:
        f.write(index)
    print("  wrote rants.html (%d post%s)" % (len(posts), "" if len(posts) == 1 else "s"))


if __name__ == "__main__":
    print("building rants...")
    build()
    print("done.")
